[project]
name = "gpt-freelance-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.30.0",
    "beautifulsoup4>=4.15.0",
    "g4f[all]>=7.9.4",
    "pydantic-settings>=2.14.2",
    "requests>=2.34.2",
]
